let specData = [
    {
        "query_spectrum_nr": "423",
        "rt_time_query_spectrum": "166.427.002",
        "precursor_mz_query_spectrum": "181.073",
        "SpectrumID_GNPS_results": "CCMSLIB00000206017",
        "Compound_Name_GNPS_results": "Massbank: Aminophylline",
        "Smiles_GNPS_results": "[H]C([H])([H])N(C(=O)1)C(=O)c(n([H])2)c(nc([H])2)N(C([H])([H])[H])1",
        "MassDiff_GNPS_results": "0.0",
        "LibMZ_GNPS_results": "181.073",
        "InChIKey-Planar_GNPS_results": "ZFXYFBGIUFBOJW",
        "superclass_GNPS_results": "Organoheterocyclic compounds",
        "ms2query_model_prediction_ms2query_results": "0.8751",
        "precursor_mz_difference_ms2query_results": "0.0",
        "precursor_mz_analog_ms2query_results": "181.073",
        "inchikey_ms2query_results": "ZFXYFBGIUFBOJW",
        "spectrum_ids_ms2query_results": "CCMSLIB00005771524",
        "analog_compound_name_ms2query_results": "Aminophylline",
        "smiles_ms2query_results": "O=C1C2=C(N=CN2)N(C)C(N1C)=O",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Organoheterocyclic compounds",
        "cf_class_ms2query_results": "Imidazopyrimidines",
        "cf_subclass_ms2query_results": "Purines and purine derivatives",
        "cf_direct_parent_ms2query_results": "Xanthines",
        "npc_class_results_ms2query_results": "Purine alkaloids",
        "npc_superclass_results_ms2query_results": "Pseudoalkaloids (transamidation)",
        "npc_pathway_results_ms2query_results": "Alkaloids"
    },
    {
        "query_spectrum_nr": "344",
        "rt_time_query_spectrum": "36.956.001",
        "precursor_mz_query_spectrum": "138.058",
        "SpectrumID_GNPS_results": "CCMSLIB00005755284",
        "Compound_Name_GNPS_results": "Massbank: N-methylnicotinate|1-methylpyridin-1-ium-3-carboxylate",
        "Smiles_GNPS_results": "C[n+]1cccc(C(=O)[O-])c1",
        "MassDiff_GNPS_results": "0.00300598",
        "LibMZ_GNPS_results": "138.055",
        "InChIKey-Planar_GNPS_results": "WWNNZCOKKKDOPX",
        "superclass_GNPS_results": "",
        "ms2query_model_prediction_ms2query_results": "0.3041",
        "precursor_mz_difference_ms2query_results": "13.982",
        "precursor_mz_analog_ms2query_results": "124.076",
        "inchikey_ms2query_results": "BHAAPTBBJKJZER",
        "spectrum_ids_ms2query_results": "CCMSLIB00005765008",
        "analog_compound_name_ms2query_results": "p-Anisidine",
        "smiles_ms2query_results": "COC1=CC=C(N)C=C1",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Benzenoids",
        "cf_class_ms2query_results": "Phenol ethers",
        "cf_subclass_ms2query_results": "Aminophenyl ethers",
        "cf_direct_parent_ms2query_results": "Aminophenyl ethers",
        "npc_class_results_ms2query_results": "",
        "npc_superclass_results_ms2query_results": "",
        "npc_pathway_results_ms2query_results": ""
    },
    {
        "query_spectrum_nr": "834",
        "rt_time_query_spectrum": "390.897.003",
        "precursor_mz_query_spectrum": "457.204",
        "SpectrumID_GNPS_results": "CCMSLIB00003137233",
        "Compound_Name_GNPS_results": "Spectral Match to Baicalin from NIST14",
        "Smiles_GNPS_results": "",
        "MassDiff_GNPS_results": "10.112",
        "LibMZ_GNPS_results": "447.092",
        "InChIKey-Planar_GNPS_results": "",
        "superclass_GNPS_results": "",
        "ms2query_model_prediction_ms2query_results": "0.5284",
        "precursor_mz_difference_ms2query_results": "65.92",
        "precursor_mz_analog_ms2query_results": "391.284",
        "inchikey_ms2query_results": "JWZBXKZZDYMDCJ",
        "spectrum_ids_ms2query_results": "CCMSLIB00005738621",
        "analog_compound_name_ms2query_results": "4-(3-hydroxy-10,13-dimethyl-6-oxo-1,2,3,4,5,7,8,9,11,12,14,15,16,17-tetradecahydrocyclopenta[a]phenanthren-17-yl)pentanoic acid",
        "smiles_ms2query_results": "C[C@@H]([C@H]1CC[C@]2([H])[C@]1(C)CC[C@@]3([H])[C@@]2([H])CC([C@@]4([H])[C@]3(C)CC[C@@H](O)C4)=O)CCC(O)=O",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Lipids and lipid-like molecules",
        "cf_class_ms2query_results": "Steroids and steroid derivatives",
        "cf_subclass_ms2query_results": "Bile acids, alcohols and derivatives",
        "cf_direct_parent_ms2query_results": "Monohydroxy bile acids, alcohols and derivatives",
        "npc_class_results_ms2query_results": "Cholane steroids",
        "npc_superclass_results_ms2query_results": "Steroids",
        "npc_pathway_results_ms2query_results": "Terpenoids"
    },
    {
        "query_spectrum_nr": "417",
        "rt_time_query_spectrum": "236.373.001",
        "precursor_mz_query_spectrum": "177.055",
        "SpectrumID_GNPS_results": "CCMSLIB00003136138",
        "Compound_Name_GNPS_results": "Spectral Match to 3-Hydroxy-4-methoxycinnamic acid from NIST14",
        "Smiles_GNPS_results": "",
        "MassDiff_GNPS_results": "0.00100708",
        "LibMZ_GNPS_results": "177.056",
        "InChIKey-Planar_GNPS_results": "",
        "superclass_GNPS_results": "",
        "ms2query_model_prediction_ms2query_results": "0.8432",
        "precursor_mz_difference_ms2query_results": "0.0",
        "precursor_mz_analog_ms2query_results": "177.055",
        "inchikey_ms2query_results": "KSEBMYQBYZTDHS",
        "spectrum_ids_ms2query_results": "CCMSLIB00003139575",
        "analog_compound_name_ms2query_results": "trans-Ferulic acid",
        "smiles_ms2query_results": "COC1=C(C=CC(=C1)/C=C/C(=O)O)O",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Phenylpropanoids and polyketides",
        "cf_class_ms2query_results": "Cinnamic acids and derivatives",
        "cf_subclass_ms2query_results": "Hydroxycinnamic acids and derivatives",
        "cf_direct_parent_ms2query_results": "Hydroxycinnamic acids",
        "npc_class_results_ms2query_results": "Cinnamic acids and derivatives",
        "npc_superclass_results_ms2query_results": "Phenylpropanoids (C6-C3)",
        "npc_pathway_results_ms2query_results": "Shikimates and Phenylpropanoids"
    },
    {
        "query_spectrum_nr": "446",
        "rt_time_query_spectrum": "59.206.001",
        "precursor_mz_query_spectrum": "204.124",
        "SpectrumID_GNPS_results": "CCMSLIB00003135497",
        "Compound_Name_GNPS_results": "Spectral Match to Acetyl-DL-carnitine from NIST14",
        "Smiles_GNPS_results": "CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C",
        "MassDiff_GNPS_results": "0.000991821",
        "LibMZ_GNPS_results": "204.123",
        "InChIKey-Planar_GNPS_results": "RDHQFKQIGNGIED",
        "superclass_GNPS_results": "Lipids and lipid-like molecules",
        "ms2query_model_prediction_ms2query_results": "0.8556",
        "precursor_mz_difference_ms2query_results": "0.001",
        "precursor_mz_analog_ms2query_results": "204.123",
        "inchikey_ms2query_results": "RDHQFKQIGNGIED",
        "spectrum_ids_ms2query_results": "CCMSLIB00006681997",
        "analog_compound_name_ms2query_results": "ACETYL-CARNITINE",
        "smiles_ms2query_results": "CC(=O)O[C@H](CC(O)=O)C[N+](C)(C)C",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Lipids and lipid-like molecules",
        "cf_class_ms2query_results": "Fatty Acyls",
        "cf_subclass_ms2query_results": "Fatty acid esters",
        "cf_direct_parent_ms2query_results": "Acyl carnitines",
        "npc_class_results_ms2query_results": "Fatty acyl carnitines",
        "npc_superclass_results_ms2query_results": "Fatty esters",
        "npc_pathway_results_ms2query_results": "Fatty acids"
    },
    {
        "query_spectrum_nr": "621",
        "rt_time_query_spectrum": "420.804.993",
        "precursor_mz_query_spectrum": "302.233",
        "SpectrumID_GNPS_results": "CCMSLIB00005885063",
        "Compound_Name_GNPS_results": "Octanoylcarnitine - 40.00 eV",
        "Smiles_GNPS_results": "CCCCCCCC(=O)O[C@H](CC(O)=O)C[N+](C)(C)C",
        "MassDiff_GNPS_results": "14.015.999.999.999.900",
        "LibMZ_GNPS_results": "288.217",
        "InChIKey-Planar_GNPS_results": "CXTATJFJDMJMIY",
        "superclass_GNPS_results": "Lipids and lipid-like molecules",
        "ms2query_model_prediction_ms2query_results": "0.6878",
        "precursor_mz_difference_ms2query_results": "84.094",
        "precursor_mz_analog_ms2query_results": "218.139",
        "inchikey_ms2query_results": "UFAHZIUFPNSHSL",
        "spectrum_ids_ms2query_results": "CCMSLIB00005885048",
        "analog_compound_name_ms2query_results": "Propionylcarnitine - 70.00 eV",
        "smiles_ms2query_results": "CCC(=O)O[C@H](CC(O)=O)C[N+](C)(C)C",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Lipids and lipid-like molecules",
        "cf_class_ms2query_results": "Fatty Acyls",
        "cf_subclass_ms2query_results": "Fatty acid esters",
        "cf_direct_parent_ms2query_results": "Acyl carnitines",
        "npc_class_results_ms2query_results": "Fatty acyl carnitines",
        "npc_superclass_results_ms2query_results": "Fatty esters",
        "npc_pathway_results_ms2query_results": "Fatty acids"
    },
    {
        "query_spectrum_nr": "892",
        "rt_time_query_spectrum": "502.499.023",
        "precursor_mz_query_spectrum": "637.356",
        "SpectrumID_GNPS_results": "CCMSLIB00005788112",
        "Compound_Name_GNPS_results": "Apigenin 7-galacturonide",
        "Smiles_GNPS_results": "C1=CC(=CC=C1C2=CC(=O)C3=C(C=C(C=C3O2)OC4C(C(C(C(O4)C(=O)O)O)O)O)O)O",
        "MassDiff_GNPS_results": "190.263",
        "LibMZ_GNPS_results": "447.093",
        "InChIKey-Planar_GNPS_results": "JBFOLLJCGUCDQP",
        "superclass_GNPS_results": "Phenylpropanoids and polyketides",
        "ms2query_model_prediction_ms2query_results": "0.7075",
        "precursor_mz_difference_ms2query_results": "292.153",
        "precursor_mz_analog_ms2query_results": "929.509",
        "inchikey_ms2query_results": "MADZMXIFUWFDJK",
        "spectrum_ids_ms2query_results": "CCMSLIB00005741392",
        "analog_compound_name_ms2query_results": "Soyasapogenol B base + O-HexA-Hex-Pen",
        "smiles_ms2query_results": "O=C(O)C8OC(OC5CCC4(C)(C(CCC2(C)(C4(CC=C1C3CC(C)(C)CC(O)C3(C)(CCC12(C)))))C5(C)(CO)))C(OC7OC(CO)C(O)C(O)C7(OC6OCC(O)C(O)C6(O)))C(O)C8(O)",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Lipids and lipid-like molecules",
        "cf_class_ms2query_results": "Prenol lipids",
        "cf_subclass_ms2query_results": "Terpene glycosides",
        "cf_direct_parent_ms2query_results": "Triterpene saponins",
        "npc_class_results_ms2query_results": "Oleanane triterpenoids",
        "npc_superclass_results_ms2query_results": "Triterpenoids",
        "npc_pathway_results_ms2query_results": "Terpenoids"
    },
    {
        "query_spectrum_nr": "727",
        "rt_time_query_spectrum": "116.612.999",
        "precursor_mz_query_spectrum": "350.088",
        "SpectrumID_GNPS_results": "CCMSLIB00003137233",
        "Compound_Name_GNPS_results": "Spectral Match to Baicalin from NIST14",
        "Smiles_GNPS_results": "",
        "MassDiff_GNPS_results": "97.004",
        "LibMZ_GNPS_results": "447.092",
        "InChIKey-Planar_GNPS_results": "",
        "superclass_GNPS_results": "",
        "ms2query_model_prediction_ms2query_results": "0.409",
        "precursor_mz_difference_ms2query_results": "83.099",
        "precursor_mz_analog_ms2query_results": "433.187",
        "inchikey_ms2query_results": "FSNCEEGOMTYXKY",
        "spectrum_ids_ms2query_results": "CCMSLIB00006673505",
        "analog_compound_name_ms2query_results": "3S_2349_Tetrahydro_1h_pyrido_34b_indole_carboxylic_acid",
        "smiles_ms2query_results": "O=C(O)C3NCC=2NC1=CC=CC=C1C=2C3",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Organoheterocyclic compounds",
        "cf_class_ms2query_results": "Indoles and derivatives",
        "cf_subclass_ms2query_results": "Pyridoindoles",
        "cf_direct_parent_ms2query_results": "Beta carbolines",
        "npc_class_results_ms2query_results": "Carboline alkaloids",
        "npc_superclass_results_ms2query_results": "Tryptophan alkaloids",
        "npc_pathway_results_ms2query_results": "Alkaloids"
    },
    {
        "query_spectrum_nr": "180",
        "rt_time_query_spectrum": "69.030.998",
        "precursor_mz_query_spectrum": "124.076",
        "SpectrumID_GNPS_results": "CCMSLIB00005750262",
        "Compound_Name_GNPS_results": "Massbank:KW102504 p-phenetidine",
        "Smiles_GNPS_results": "CCOc1ccc(N)cc1",
        "MassDiff_GNPS_results": "14.015",
        "LibMZ_GNPS_results": "138.091",
        "InChIKey-Planar_GNPS_results": "IMPPGHMHELILKG",
        "superclass_GNPS_results": "Benzenoids",
        "ms2query_model_prediction_ms2query_results": "0.2939",
        "precursor_mz_difference_ms2query_results": "173.955",
        "precursor_mz_analog_ms2query_results": "298.031",
        "inchikey_ms2query_results": "KXNXWINFSDKMHD",
        "spectrum_ids_ms2query_results": "CCMSLIB00000207770",
        "analog_compound_name_ms2query_results": "N-[4-(1,3-thiazol-2-ylsulfamoyl)phenyl]acetamide",
        "smiles_ms2query_results": "c1(ccc(NC(=O)C)cc1)S(=O)(NC2=NC=CS2)=O",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Benzenoids",
        "cf_class_ms2query_results": "Benzene and substituted derivatives",
        "cf_subclass_ms2query_results": "Benzenesulfonamides",
        "cf_direct_parent_ms2query_results": "Benzenesulfonamides",
        "npc_class_results_ms2query_results": "",
        "npc_superclass_results_ms2query_results": "",
        "npc_pathway_results_ms2query_results": "Alkaloids"
    },
    {
        "query_spectrum_nr": "605",
        "rt_time_query_spectrum": "338.711.975",
        "precursor_mz_query_spectrum": "286.202",
        "SpectrumID_GNPS_results": "CCMSLIB00005885058",
        "Compound_Name_GNPS_results": "Isovalerylcarnitine - 50.00 eV",
        "Smiles_GNPS_results": "CC(C)CC(=O)OC(CC([O-])=O)C[N+](C)(C)C",
        "MassDiff_GNPS_results": "40.032",
        "LibMZ_GNPS_results": "246.17",
        "InChIKey-Planar_GNPS_results": "IGQBPDJNUXPEMT",
        "superclass_GNPS_results": "Lipids and lipid-like molecules",
        "ms2query_model_prediction_ms2query_results": "0.7843",
        "precursor_mz_difference_ms2query_results": "0.001",
        "precursor_mz_analog_ms2query_results": "286.201",
        "inchikey_ms2query_results": "LOSHAHDSFZXVCT",
        "spectrum_ids_ms2query_results": "CCMSLIB00006581932",
        "analog_compound_name_ms2query_results": "(2E)-octenoylcarnitine",
        "smiles_ms2query_results": "",
        "cf_kingdom_ms2query_results": "",
        "cf_superclass_ms2query_results": "",
        "cf_class_ms2query_results": "",
        "cf_subclass_ms2query_results": "",
        "cf_direct_parent_ms2query_results": "",
        "npc_class_results_ms2query_results": "",
        "npc_superclass_results_ms2query_results": "",
        "npc_pathway_results_ms2query_results": ""
    },
    {
        "query_spectrum_nr": "827",
        "rt_time_query_spectrum": "326.290.009",
        "precursor_mz_query_spectrum": "443.13",
        "SpectrumID_GNPS_results": "CCMSLIB00000222538",
        "Compound_Name_GNPS_results": "Massbank:PB006265 4-methylumbelliferyl glucuronide|(2S,3S,4S,5R,6S)-3,4,5-trihydroxy-6-(4-methyl-2-oxochromen-7-yl)oxyoxane-2-carboxylic acid",
        "Smiles_GNPS_results": "CC1=CC(=O)OC2=C1C=CC(=C2)OC3C(C(C(C(O3)C(=O)O)O)O)O",
        "MassDiff_GNPS_results": "9.004.299.999.999.990",
        "LibMZ_GNPS_results": "353.087",
        "InChIKey-Planar_GNPS_results": "ARQXEQLMMNGFDU",
        "superclass_GNPS_results": "Phenylpropanoids and polyketides",
        "ms2query_model_prediction_ms2query_results": "0.409",
        "precursor_mz_difference_ms2query_results": "215.95",
        "precursor_mz_analog_ms2query_results": "659.08",
        "inchikey_ms2query_results": "RNKMOGIPOMVCHO",
        "spectrum_ids_ms2query_results": "CCMSLIB00006554680",
        "analog_compound_name_ms2query_results": "1,3,6-Tri-O-galloyl-beta-D-glucose",
        "smiles_ms2query_results": "O[C@@H]1[C@@H](COC(=O)C2=CC(O)=C(O)C(O)=C2)O[C@@H](OC(=O)C3=CC(O)=C(O)C(O)=C3)[C@H](O)[C@H]1OC(=O)C4=CC(O)=C(O)C(O)=C4",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Phenylpropanoids and polyketides",
        "cf_class_ms2query_results": "Tannins",
        "cf_subclass_ms2query_results": "",
        "cf_direct_parent_ms2query_results": "Tannins",
        "npc_class_results_ms2query_results": "Gallotannins",
        "npc_superclass_results_ms2query_results": "Phenolic acids (C6-C1)",
        "npc_pathway_results_ms2query_results": "Shikimates and Phenylpropanoids"
    },
    {
        "query_spectrum_nr": "411",
        "rt_time_query_spectrum": "313.561.981",
        "precursor_mz_query_spectrum": "170.06",
        "SpectrumID_GNPS_results": "CCMSLIB00005746579",
        "Compound_Name_GNPS_results": "Massbank:PR301031 Harmane",
        "Smiles_GNPS_results": "CC1=C2NC3=CC=CC=C3C2=CC=N1",
        "MassDiff_GNPS_results": "13.032",
        "LibMZ_GNPS_results": "183.092",
        "InChIKey-Planar_GNPS_results": "PSFDQSOCUJVVGF",
        "superclass_GNPS_results": "",
        "ms2query_model_prediction_ms2query_results": "0.6246",
        "precursor_mz_difference_ms2query_results": "0.0",
        "precursor_mz_analog_ms2query_results": "170.06",
        "inchikey_ms2query_results": "PLVPPLCLBIEYEA",
        "spectrum_ids_ms2query_results": "CCMSLIB00006705962",
        "analog_compound_name_ms2query_results": "3-Indoleacrylic acid",
        "smiles_ms2query_results": "C1=CC=C2C(=C1)C(=CN2)/C=C/C(=O)O",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Organoheterocyclic compounds",
        "cf_class_ms2query_results": "Indoles and derivatives",
        "cf_subclass_ms2query_results": "Indoles",
        "cf_direct_parent_ms2query_results": "Indoles",
        "npc_class_results_ms2query_results": "Simple indole alkaloids",
        "npc_superclass_results_ms2query_results": "Tryptophan alkaloids",
        "npc_pathway_results_ms2query_results": "Alkaloids"
    },
    {
        "query_spectrum_nr": "432",
        "rt_time_query_spectrum": "156.485.001",
        "precursor_mz_query_spectrum": "197.068",
        "SpectrumID_GNPS_results": "CCMSLIB00000206017",
        "Compound_Name_GNPS_results": "Massbank: Aminophylline",
        "Smiles_GNPS_results": "[H]C([H])([H])N(C(=O)1)C(=O)c(n([H])2)c(nc([H])2)N(C([H])([H])[H])1",
        "MassDiff_GNPS_results": "15.995",
        "LibMZ_GNPS_results": "181.073",
        "InChIKey-Planar_GNPS_results": "ZFXYFBGIUFBOJW",
        "superclass_GNPS_results": "Organoheterocyclic compounds",
        "ms2query_model_prediction_ms2query_results": "0.8158",
        "precursor_mz_difference_ms2query_results": "0.001",
        "precursor_mz_analog_ms2query_results": "197.067",
        "inchikey_ms2query_results": "NOFNCLGCUJJPKU",
        "spectrum_ids_ms2query_results": "CCMSLIB00006679631",
        "analog_compound_name_ms2query_results": "\"1,7-DIMETHYLURIC ACID\"",
        "smiles_ms2query_results": "CN1C2=C(NC1=O)NC(=O)N(C2=O)C",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Organoheterocyclic compounds",
        "cf_class_ms2query_results": "Imidazopyrimidines",
        "cf_subclass_ms2query_results": "Purines and purine derivatives",
        "cf_direct_parent_ms2query_results": "Xanthines",
        "npc_class_results_ms2query_results": "Purine alkaloids",
        "npc_superclass_results_ms2query_results": "Pseudoalkaloids (transamidation)",
        "npc_pathway_results_ms2query_results": "Alkaloids"
    },
    {
        "query_spectrum_nr": "390",
        "rt_time_query_spectrum": "173.839.996",
        "precursor_mz_query_spectrum": "147.045",
        "SpectrumID_GNPS_results": "CCMSLIB00006422084",
        "Compound_Name_GNPS_results": "Isodemethylwedelolactone",
        "Smiles_GNPS_results": "O=C1OC=2C(O)=CC(O)=CC2C=3OC=4C=C(O)C(O)=CC4C13",
        "MassDiff_GNPS_results": "153.985",
        "LibMZ_GNPS_results": "301.03",
        "InChIKey-Planar_GNPS_results": "OBEHELRBTWMPHI",
        "superclass_GNPS_results": "Phenylpropanoids and polyketides",
        "ms2query_model_prediction_ms2query_results": "0.6241",
        "precursor_mz_difference_ms2query_results": "0.0",
        "precursor_mz_analog_ms2query_results": "147.045",
        "inchikey_ms2query_results": "ZYGHJZDHTFUPRJ",
        "spectrum_ids_ms2query_results": "CCMSLIB00000215130",
        "analog_compound_name_ms2query_results": "FIO00037 Coumarin",
        "smiles_ms2query_results": "O=C1OC2=CC=CC=C2C=C1",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Phenylpropanoids and polyketides",
        "cf_class_ms2query_results": "Coumarins and derivatives",
        "cf_subclass_ms2query_results": "",
        "cf_direct_parent_ms2query_results": "Coumarins and derivatives",
        "npc_class_results_ms2query_results": "Simple coumarins",
        "npc_superclass_results_ms2query_results": "Coumarins",
        "npc_pathway_results_ms2query_results": "Shikimates and Phenylpropanoids"
    },
    {
        "query_spectrum_nr": "839",
        "rt_time_query_spectrum": "490.235.016",
        "precursor_mz_query_spectrum": "467.153",
        "SpectrumID_GNPS_results": "CCMSLIB00003137233",
        "Compound_Name_GNPS_results": "Spectral Match to Baicalin from NIST14",
        "Smiles_GNPS_results": "",
        "MassDiff_GNPS_results": "20.061",
        "LibMZ_GNPS_results": "447.092",
        "InChIKey-Planar_GNPS_results": "",
        "superclass_GNPS_results": "",
        "ms2query_model_prediction_ms2query_results": "0.5309",
        "precursor_mz_difference_ms2query_results": "192.083",
        "precursor_mz_analog_ms2query_results": "275.07",
        "inchikey_ms2query_results": "QKNDCRMJDZLFEG",
        "spectrum_ids_ms2query_results": "CCMSLIB00006384850",
        "analog_compound_name_ms2query_results": "7-methoxy-2-phenyl-4H-chromen-4-one",
        "smiles_ms2query_results": "O=C1C=C(OC2=CC(OC)=CC=C12)C=3C=CC=CC3",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Phenylpropanoids and polyketides",
        "cf_class_ms2query_results": "Flavonoids",
        "cf_subclass_ms2query_results": "O-methylated flavonoids",
        "cf_direct_parent_ms2query_results": "7-O-methylated flavonoids",
        "npc_class_results_ms2query_results": "Flavones",
        "npc_superclass_results_ms2query_results": "Flavonoids",
        "npc_pathway_results_ms2query_results": "Shikimates and Phenylpropanoids"
    },
    {
        "query_spectrum_nr": "408",
        "rt_time_query_spectrum": "66.576.996",
        "precursor_mz_query_spectrum": "169.036",
        "SpectrumID_GNPS_results": "CCMSLIB00005883631",
        "Compound_Name_GNPS_results": "URATE - 50.0 eV",
        "Smiles_GNPS_results": "O=C1NC2=C(N1)C(=O)NC(=O)N2",
        "MassDiff_GNPS_results": "0.0",
        "LibMZ_GNPS_results": "169.036",
        "InChIKey-Planar_GNPS_results": "LEHOTFFKMJEONL",
        "superclass_GNPS_results": "Organoheterocyclic compounds",
        "ms2query_model_prediction_ms2query_results": "0.733",
        "precursor_mz_difference_ms2query_results": "0.0",
        "precursor_mz_analog_ms2query_results": "169.036",
        "inchikey_ms2query_results": "LEHOTFFKMJEONL",
        "spectrum_ids_ms2query_results": "CCMSLIB00005883629",
        "analog_compound_name_ms2query_results": "URATE - 30.0 eV",
        "smiles_ms2query_results": "C12=C(NC(=O)N1)NC(=O)NC2=O",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Organoheterocyclic compounds",
        "cf_class_ms2query_results": "Imidazopyrimidines",
        "cf_subclass_ms2query_results": "Purines and purine derivatives",
        "cf_direct_parent_ms2query_results": "Xanthines",
        "npc_class_results_ms2query_results": "Purine alkaloids",
        "npc_superclass_results_ms2query_results": "Pseudoalkaloids (transamidation)",
        "npc_pathway_results_ms2query_results": "Alkaloids"
    },
    {
        "query_spectrum_nr": "468",
        "rt_time_query_spectrum": "99.003.006",
        "precursor_mz_query_spectrum": "218.139",
        "SpectrumID_GNPS_results": "CCMSLIB00003135497",
        "Compound_Name_GNPS_results": "Spectral Match to Acetyl-DL-carnitine from NIST14",
        "Smiles_GNPS_results": "CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C",
        "MassDiff_GNPS_results": "14.015.999.999.999.900",
        "LibMZ_GNPS_results": "204.123",
        "InChIKey-Planar_GNPS_results": "RDHQFKQIGNGIED",
        "superclass_GNPS_results": "Lipids and lipid-like molecules",
        "ms2query_model_prediction_ms2query_results": "0.7843",
        "precursor_mz_difference_ms2query_results": "0.0",
        "precursor_mz_analog_ms2query_results": "218.139",
        "inchikey_ms2query_results": "UFAHZIUFPNSHSL",
        "spectrum_ids_ms2query_results": "CCMSLIB00005885046",
        "analog_compound_name_ms2query_results": "Propionylcarnitine - 50.00 eV",
        "smiles_ms2query_results": "CCC(=O)O[C@H](CC(O)=O)C[N+](C)(C)C",
        "cf_kingdom_ms2query_results": "Organic compounds",
        "cf_superclass_ms2query_results": "Lipids and lipid-like molecules",
        "cf_class_ms2query_results": "Fatty Acyls",
        "cf_subclass_ms2query_results": "Fatty acid esters",
        "cf_direct_parent_ms2query_results": "Acyl carnitines",
        "npc_class_results_ms2query_results": "Fatty acyl carnitines",
        "npc_superclass_results_ms2query_results": "Fatty esters",
        "npc_pathway_results_ms2query_results": "Fatty acids"
    },
];


console.log(specData);

  function sumMasses(group) {
    return d3.sum(group, function(d) {
      return d.MassDiff_GNPS_results;
    });
  }
  
  let specGroups = d3.rollup(specData,
                         sumMasses,
                         function(d) { return d.cf_superclass_ms2query_results; },
                         function(d) { return d.cf_class_ms2query_results; }
                        );
console.log(specGroups.get('Benzenoids'));



